import { facetValues, filterWithFacets } from "./search.mjs";
import { financialMetricDisplay, formatMoney, fundraisingDisplay, fundingSourceLabel, sourceRecordLocator, taxonomyHeading } from "./presentation.mjs";
import { correctionUrl } from "./corrections.mjs";

const state = { entities: [], similarities: [], filtered: [], selectedId: null, facets: {} };
const els = { search: document.querySelector("#search"), results: document.querySelector("#results"), count: document.querySelector("#result-count"), card: document.querySelector("#card"), feedback: document.querySelector("#feedback-link"), facets: document.querySelector("#facets") };
const esc = value => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const abn = entity => entity.external_identifiers?.find(item => item.scheme.toLowerCase() === "abn")?.value;
const httpUrl = value => /^https?:\/\//i.test(value ?? "") ? value : `https://${value}`;
const cardUrl = entity => entity.canonical_url ?? `${location.origin}${location.pathname}#${encodeURIComponent(entity.causebase_id)}`;
const label = value => value.split(":").at(-1).replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const list = (values, empty = "None recorded") => values?.length ? `<ul>${values.map(value => `<li>${esc(value)}</li>`).join("")}</ul>` : `<p>${empty}</p>`;

function citations(entity) { return new Map([...new Set([...(entity.summary_evidence_ids ?? []), ...(entity.evidence ?? []).map(item => item.evidence_id)])].map((id, index) => [id, index + 1])); }
function cite(ids, registry) { return (ids ?? []).filter(id => registry.has(id)).map(id => `<a class="citation" href="#reference-${registry.get(id)}" aria-label="Reference ${registry.get(id)}">[${registry.get(id)}]</a>`).join(" "); }
function syncUrl(push = false) { const params = new URLSearchParams(); if (els.search.value) params.set("q", els.search.value); for (const [group, values] of Object.entries(state.facets)) if (values.length) params.set(group, values.join(",")); history[push ? "pushState" : "replaceState"]({}, "", `${location.pathname}${params.size ? `?${params}` : ""}${state.selectedId ? `#${encodeURIComponent(state.selectedId)}` : ""}`); }
function readUrl() { const params = new URLSearchParams(location.search); els.search.value = params.get("q") ?? ""; state.facets = {}; for (const [key, value] of params) if (key !== "q") state.facets[key] = value.split(",").filter(Boolean); state.selectedId = decodeURIComponent(location.hash.slice(1)); }

function renderFacets() {
  const labels = { geography: "Geography", cause: "CauseBase cause/domain", beneficiary: "CauseBase beneficiaries", activity: "CauseBase activity", participation: "CauseBase participation", acnc_classification: "ACNC classifications", funding: "Funding sources", dgr: "DGR status" };
  els.facets.innerHTML = Object.entries(facetValues(state.entities)).map(([group, values]) => !values.length ? "" : `<details class="facet-group"><summary>${labels[group]}${state.facets[group]?.length ? ` (${state.facets[group].length})` : ""}</summary><div>${values.map(value => `<button class="facet ${state.facets[group]?.includes(value) ? "active" : ""}" data-group="${group}" data-value="${esc(value)}">${esc(label(value))}</button>`).join("")}</div></details>`).join("");
  els.facets.querySelectorAll(".facet").forEach(button => button.onclick = () => { const selected = state.facets[button.dataset.group] ?? []; state.facets[button.dataset.group] = selected.includes(button.dataset.value) ? selected.filter(value => value !== button.dataset.value) : [...selected, button.dataset.value]; apply(); });
}
function renderResults() { els.count.textContent = `${state.filtered.length} organisations`; els.results.innerHTML = state.filtered.map(entity => `<button class="result ${entity.causebase_id === state.selectedId ? "selected" : ""}" data-id="${esc(entity.causebase_id)}"><strong>${esc(entity.display_name)}</strong><span>${esc(entity.navigation_geography?.find(item => item.level === "state_territory")?.label ?? entity.principal_location ?? "")}</span></button>`).join(""); els.results.querySelectorAll("button").forEach(button => button.onclick = () => select(button.dataset.id)); }
function externalLinks(entity) { const number = abn(entity), acnc = entity.acnc_profile_url ?? `https://www.acnc.gov.au/charity/charities?search=${encodeURIComponent(number ?? entity.display_name)}`; return `<ul class="link-list">${entity.website ? `<li><a href="${esc(httpUrl(entity.website))}" target="_blank" rel="noreferrer">Organisation website</a></li>` : ""}${number ? `<li><a href="https://abr.business.gov.au/ABN/View?abn=${encodeURIComponent(number)}" target="_blank" rel="noreferrer">ABN ${esc(number)}</a></li>` : ""}<li><a href="${esc(acnc)}" target="_blank" rel="noreferrer">${entity.acnc_profile_url ? "ACNC Charity Register profile" : "Search ACNC Charity Register"}</a></li>${entity.acnc_ais_url ? `<li><a href="${esc(entity.acnc_ais_url)}" target="_blank" rel="noreferrer">Latest ACNC AIS</a></li>` : ""}<li><a href="${esc(cardUrl(entity))}">Copy/share card link</a></li><li><a href="./public/data/cards/${encodeURIComponent(entity.causebase_id)}.json">Card JSON</a></li><li><a href="./public/data/cards/${encodeURIComponent(entity.causebase_id)}.md">Card Markdown</a></li></ul>`; }
function lineItems(items, registry) { return items?.length ? `<ul>${items.map(item => `<li>${esc(item.label)}: ${esc(formatMoney(item.amount?.normalised_amount, item.amount?.normalised_currency))} ${cite(item.evidence_ids, registry)}</li>`).join("")}</ul>` : ""; }
function renderCard(entity) {
  const registry = citations(entity); const taxonomies = new Map(); for (const item of entity.classifications ?? []) { if (!taxonomies.has(item.taxonomy_id)) taxonomies.set(item.taxonomy_id, []); taxonomies.get(item.taxonomy_id).push(item); }
  const refs = [...registry.entries()].map(([id, number]) => { const item = entity.evidence.find(value => value.evidence_id === id); return item ? `<li id="reference-${number}"><strong>[${number}] ${esc(item.title)}</strong> — ${esc(item.publisher ?? item.source_type)}, observed ${esc(item.observed_at)}${item.page ? `, p. ${item.page}` : ""}${item.url ? ` · <a href="${esc(item.url)}" target="_blank" rel="noreferrer">Open source</a>` : ""}</li>` : ""; }).join("");
  const finance = entity.financial_records?.at(-1); const financeIds = entity.financial_records?.flatMap(item => item.evidence_ids) ?? [];
  const funding = entity.funding_sources?.map(item => `<li>${esc(fundingSourceLabel(item.source_type))}${item.amount ? `: ${esc(formatMoney(item.amount.normalised_amount, item.amount.normalised_currency))}` : ""} ${cite(item.evidence_ids, registry)}</li>`).join("");
  const participation = entity.participation_observations?.map(item => `<li>${esc(item.label)} ${cite(item.evidence_ids, registry)}</li>`).join("");
  els.card.innerHTML = `<header class="card-header"><div><p class="eyebrow">CauseBase card</p><h1>${esc(entity.display_name)}</h1><p>${esc(entity.legal_name)} · <a href="#${encodeURIComponent(entity.causebase_id)}">${esc(entity.causebase_id)}</a></p></div>${externalLinks(entity)}</header>
    <section><div class="section-title"><h2>About</h2><a class="edit-link" href="${correctionUrl(entity, "causebase_summary", entity.causebase_summary, cardUrl(entity))}">Suggest correction</a></div><p class="summary">${esc(entity.causebase_summary)} ${cite(entity.summary_evidence_ids, registry)}</p>${entity.operating_names?.length ? `<p><strong>Also known as:</strong> ${esc(entity.operating_names.join(", "))}</p>` : ""}<p><strong>Principal location:</strong> ${esc(entity.principal_location ?? "Not recorded")}</p></section>
    <section class="columns"><div><h2>Activities</h2>${list(entity.activities)}</div><div><h2>Beneficiaries</h2>${list(entity.beneficiaries)}</div><div><h2>Geography</h2>${list(entity.geography)}</div></section>
    <section><h2>Programs</h2>${entity.programs?.length ? entity.programs.map(program => `<article><h3>${esc(program.name)}</h3><p>${esc(program.description ?? "")}</p><p>${esc([...(program.beneficiaries ?? []), ...(program.geography ?? [])].join(" · "))} ${cite(program.evidence_ids, registry)}</p></article>`).join("") : "<p>Program-level records have not yet been processed from the acquired sources.</p>"}</section>
    <section><h2>Participation</h2>${participation ? `<ul>${participation}</ul>` : "<p>Participation opportunities have not yet been processed from the acquired sources.</p>"}</section>
    <section><h2>Financials</h2><dl class="facts"><div><dt>Revenue</dt><dd>${esc(financialMetricDisplay(entity, "revenue"))} ${cite(financeIds, registry)}</dd></div><div><dt>Total expenses</dt><dd>${esc(financialMetricDisplay(entity, "total_expenses"))} ${cite(financeIds, registry)}</dd></div><div><dt>Fundraising expenditure</dt><dd>${esc(fundraisingDisplay(entity))}</dd></div></dl>${finance ? `<h3>Income detail</h3>${lineItems(finance.income_breakdown, registry)}<h3>Expense detail</h3>${lineItems(finance.expense_breakdown, registry)}<h3>Balance sheet detail</h3>${lineItems(finance.balance_sheet_breakdown, registry)}` : ""}</section>
    <section><h2>Funding &amp; fundraising</h2>${funding ? `<h3>Funding sources</h3><ul>${funding}</ul>` : "<p>Funding sources: <strong>not_available_from_source</strong> in the currently acquired evidence.</p>"}<p class="muted">This section is descriptive and is not a rating or efficiency assessment.</p></section>
    <section><h2>Classifications</h2>${[...taxonomies.entries()].map(([taxonomy, items]) => `<div class="taxonomy-block"><h3>${esc(taxonomyHeading(taxonomy))}</h3><div class="chips">${items.map(item => `<button class="chip" data-taxonomy="${esc(taxonomy)}" data-term="${esc(item.term_id)}">${esc(item.term_label)} ${cite(item.evidence_ids, registry)}</button>`).join("")}</div></div>`).join("") || "<p>None recorded</p>"}</section>
    <section><h2>Source-native records</h2><ul>${(entity.source_native_records ?? []).map(item => `<li><a href="${sourceRecordLocator(item)}">${esc(item.source_family)} record</a> · ${esc(item.dataset_version)}</li>`).join("") || "<li>None recorded</li>"}</ul></section><section><h2>References</h2><ol class="evidence-list">${refs}</ol></section><section><h2>External links &amp; developer data</h2>${externalLinks(entity)}</section><footer>CauseBase ${esc(entity.dataset_version)} · card schema ${esc(entity.card_schema_version)} · editorial policy ${esc(entity.editorial_policy_version)}</footer>`;
  els.card.querySelectorAll(".chip[data-taxonomy='causebase']").forEach(button => button.onclick = () => { const group = button.dataset.term.split(".")[0]; if (["cause", "beneficiary", "activity", "participation"].includes(group)) { state.facets[group] = [button.dataset.term]; apply(); } });
}
function renderSimilar(entity) { const rows = state.similarities.filter(item => item.causebase_id === entity.causebase_id).sort((a, b) => a.rank - b.rank).map(item => state.entities.find(value => value.causebase_id === item.similar_causebase_id)).filter(Boolean); if (!rows.length) return; const section = document.createElement("section"); section.innerHTML = `<h2>Similar organisations</h2><p class="muted">Descriptive semantic neighbours, not recommendations.</p><ul>${rows.map(item => `<li><button class="link-button" data-similar="${esc(item.causebase_id)}">${esc(item.display_name)}</button></li>`).join("")}</ul>`; els.card.insertBefore(section, els.card.querySelector("footer")); section.querySelectorAll("[data-similar]").forEach(button => button.onclick = () => select(button.dataset.similar)); }
function select(id, push = true) { if (!state.entities.some(entity => entity.causebase_id === id)) return; state.selectedId = id; syncUrl(push); renderResults(); const entity = state.entities.find(item => item.causebase_id === id); renderCard(entity); renderSimilar(entity); }
function apply() { state.filtered = filterWithFacets(state.entities, els.search.value, state.facets); if (!state.filtered.some(entity => entity.causebase_id === state.selectedId)) state.selectedId = state.filtered[0]?.causebase_id ?? null; syncUrl(); renderFacets(); renderResults(); if (state.selectedId) { const entity = state.entities.find(item => item.causebase_id === state.selectedId); renderCard(entity); renderSimilar(entity); } else els.card.innerHTML = "<div class=\"empty\">No organisations match these filters.</div>"; }
async function init() { try { const [data, similarities] = await Promise.all([fetch("./public/data/causebase.json").then(response => response.json()), fetch("./public/data/similarities.json").then(response => response.json()).catch(() => [])]); state.entities = data.entities; state.similarities = similarities; readUrl(); state.filtered = state.entities; if (!state.entities.some(entity => entity.causebase_id === state.selectedId)) state.selectedId = state.entities[0]?.causebase_id; els.feedback.href = correctionUrl(null, "general_feedback", "", location.href); els.search.oninput = apply; addEventListener("popstate", () => { readUrl(); apply(); }); apply(); } catch (error) { els.card.textContent = `CauseBase data could not be loaded: ${error.message}`; } }
init();
